version: '1.0'
name: my-flask-app
services:
  app:
    build:
      context: .
      docker:
        target: production
    environment:
      - OPENCV_SKIP_LOADEXT_MODULES=1
    apt:
      packages:
        - libgl1-mesa-glx
